### ISSUE TITLE
Random disconnections?!

### ISSUE THREAD

**Issue by Chreece** [barban-dev/homeassistant-midea-dehumidifier#14]
Thank you very much for your efforts and time with on the Integration.
It really helps me control the humidity in my home, in a better a smarter way...

Unfortunately I have been getting some disconnections in random times since a while ago...

During these I cannot control the device and the humidity level from device stays still or goes to Unavavailable.

The integration cannot connect any more on the dehumidifier and I'm getting the included logs.
The problem persist until I reboot the Raspberry Pi or at random goes away and I get back control.

> 2021-02-17 19:15:55 WARNING (MainThread) [homeassistant.helpers.entity] Update of humidifier.midea_dehumidifier_17592186046181 is taking over 10 seconds
> 2021-02-17 19:15:57 ERROR (SyncWorker_12) [root] MideaClient::send_api_request: errorCode=3176, errorMessage="The asyn reply does not exist "
> 2021-02-17 19:15:57 ERROR (SyncWorker_12) [root] MideaClient::appliance_transparent_send: result=ERROR in API response: result key not found
> 2021-02-17 19:15:57 ERROR (SyncWorker_12) [root] MideaClient::get_device_status: invalid API response
> 2021-02-17 19:15:57 ERROR (MainThread) [custom_components.midea_dehumidifier.humidifier] midea-dehumidifier: get_device_status ERROR.

Is it me?!
I have AdGuard but the address mapp.appsmb.com that needed for the app to communicate is in the whitelist.

**Comment by Chreece** [comment]
I should also mention that I can always control the device with the INVmateII android application

**Comment by barban-dev** [comment]
Server side issue, not directly related to this integration.
