### ISSUE TITLE
Warning with 2021.4.X

### ISSUE THREAD

**Issue by maury77** [barban-dev/homeassistant-midea-dehumidifier#24]
No 'version' key in the manifest file for custom integration 'midea_dehumidifier'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'midea_dehumidifier'

**Comment by drthanwho** [comment]
A duplicate of #18 

Also it has just been merged with this PR #16  so it can be closed 👍
