### ISSUE TITLE
Inventor Eva II PRO WiFi Vs Inventor Eva PRO WiFi on Amazon

### ISSUE THREAD

**Issue by pitoganzado** [barban-dev/homeassistant-midea-dehumidifier#26]
Hi to all! I cant find the Inventor Eva II PRO WiFi on Amazon, only the V1.
Beside this, "Info about the dehumidifier appliance can be found [here](https://www.inventorappliances.com/dehumidifiers/eva-ii-pro-wi-fi-20l)." output is "Page not found". 
They stop selling the V2 version? Thank you!

**Comment by barban-dev** [comment]
Please refers to the updated README.md for the new models working with this integration.
Cheers.
