### ISSUE TITLE
Component stopped working today

### ISSUE THREAD

**Issue by obaldius** [barban-dev/homeassistant-midea-dehumidifier#44]
Hi guys.

Today my EVA II pro Wifi dehumidifier stopped working. When I try to turn it on or off, it yields some errors. Is this happening to somebody else?

MideaClient::send_api_request: errorCode=1001, errorMessage=“Invalid param wrong format: shadow_control_async response:null”

**Comment by AlexHowser** [comment]
Same issues here.

**Comment by herr2d2** [comment]
Same problem here …

**Comment by NickDevoctomy** [comment]
Exactly the same issue here.

**Comment by fmmsfz** [comment]
Same here...

**Comment by carlososvonknossos** [comment]
It's not only that, the Midea App is also not working, there could be a problem in the Midea cloud comunication. At the same time I recorded many deauthentications of the device analyzed after this model:

https://www.researchgate.net/figure/Analyzing-Deauthentication-Attack-in-Wireshark-The-resulting-info-can-be-concluded-from_fig9_283354063

**Comment by NickDevoctomy** [comment]
More some reason my NetHome Plus app still works fine.

**Comment by herr2d2** [comment]
I can control my device with the Midea App, only the HA integration has some trouble.

**Comment by AlexHowser** [comment]
It just started working again. seems like it was oem related.

**Comment by NickDevoctomy** [comment]
Wohoo! Same here.
