### ISSUE TITLE
Usage of device_state_attributes is deprecated in Home Assistant 2021.12.0

### ISSUE THREAD

**Issue by mcv93us** [barban-dev/homeassistant-midea-dehumidifier#45]
According to Home Assistant 2021.12.0, the use of device_state_attributes has been deprecated. I think extra_state_attributes should be used from now on (see Home Assistant's Github Beta channel for more info).

Environment
Supervised home assistant 2021.12.0

Steps to reproduce
Upgrade from Home Assistant 2021.11.5 to 2021.12.0
In the log log is the following error:

Logger: homeassistant.helpers.entity
Source: helpers / entity.py: 549
First occurred: 14:33:13 (5 occurrences)
Last logged: 14:35:13

Entity humidifier.midea_dehumidifier_xxxxxxxxxxxxxx (<class 'custom_components.midea_dehumidifier.humidifier.MideaDehumidifierDevice'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by HVPereira** [comment]
Do you know if we can just replace the code on entity.py and fix it?

**Comment by mcv93us** [comment]
I solved by reading this post:
https://github.com/thomasloven/hass-browser_mod/pull/276
and changing line 272 of the humidifier.py file from
def device_state_attributes(self):
to
def extra_state_attributes(self):
after a restart of HA the error is gone!

**Comment by drthanwho** [comment]
I made a PR #42 for it already a month ago when this change was still in the dev branch but unfortunately @barban-dev hasn't updated the code yet

**Comment by sprocket7** [comment]
You saved my life ;-) Or rather, my basement is saved! Many Thanks

**Comment by barban-dev** [comment]
merged
