### ISSUE TITLE
No current humidity attribute

### ISSUE THREAD

**Issue by ecoen66** [barban-dev/homeassistant-midea-dehumidifier#57]
Although the integration works with my Midea dehumidifier (MAD50PS1QGR) in all other respects, there is no attribute for current humidity.  Also, the separate _humidity sensor from the integration reads Unknown.  In the INVmate II app, the dehumidifier does show the current humidity level.

**Comment by ecoen66** [comment]
It seems to be fixed by #42

**Comment by dellorogiulio** [comment]
Hi @ecoen66  , I recently forked both hacs and python repo to fix this annoying problem and to reduced the polling rate from 5 to 1 minute. If you wanna try (I use this version already, you can look for the _EVA II PRO WiFi Midea Inventor Dehumidifier custom integration V2_  directly  the HACS integrations.
Please make sure to link [my repository](https://github.com/dellorogiulio/homeassistant-midea-dehumidifier) and not the original one.

**Comment by cannondale0815** [comment]
@dellorogiulio I cannot find your forked repository in HACS, only the original one here. Also, are you looking to continue maintaining your forked repository, or did you just do it for this one fix (because this one isn't actively maintained anymore)?

**Comment by mourmeer** [comment]
does not work for me. I get an error. still an unknown current-humidity

**Comment by barban-dev** [comment]
fixed
