### ISSUE TITLE
Support for full water bucket

### ISSUE THREAD

**Issue by Mace404** [barban-dev/homeassistant-midea-dehumidifier#6]
Hi,

Been using this integration with my Eva II Pro and it works great!
I do miss the status in HA of the water bucket when it's full.
The NetHome Plus app on my phone gives a status "Bucket is full".

Is it possible to add this status to Home Assistant (as binary_sensor for example)

**Comment by HVPereira** [comment]
I believe that someone already managed to add this in the home assistant forum

**Comment by Spirineu** [comment]
Hi @Mace404  I couldn't add it 100% it it says that:

"The following integrations and platforms could not be set up:
midea_dehumidifier"

Did you had this issue?

**Comment by HVPereira** [comment]
You can have this by adding the following:

            self._tankShow = self._client.deviceStatus.tankShow 

in line 439 of humidifier.py and...

       self._tankShow = False

in line 180 of the same file and...

    @property
    def tank_show(self):
        """Return the current humidity."""
        return self._tankShow

in line 259

**Comment by barban-dev** [comment]
source code updated. thanks.

**Comment by barban-dev** [comment]
enhanced inserted in v. 1.0.2
