### ISSUE TITLE
Midea app migration to MSmartHome app?

### ISSUE THREAD

**Issue by cannondale0815** [barban-dev/homeassistant-midea-dehumidifier#61]
The Midea app on my Android device is reminding me to migrate to the new MSmartHome app (deadline Dec 31, 2023).

Does anyone know if migrating to this new app would break this integration? It's unclear if it's just a new frontend or if it also entails the migration of the account to a different backend.

Thanks!

**Comment by tmchow** [comment]
Can you give an update on whether it broke the integration?

**Comment by cannondale0815** [comment]
I haven't migrated to the new app yet.

Both the "Midea Air" app (on Android) and the HA integration still work as of this moment. And the app doesn't show me the migration reminder anymore, for whatever that's worth.
