### ISSUE TITLE
iOS App login: Inventor Control or INVmate II?

### ISSUE THREAD

**Issue by jlm70** [barban-dev/homeassistant-midea-dehumidifier#62]
Hi/Ciao,
just purchased an EVA ION Pro Wifi, but - as instructed in the manual - I'm using the Inventor Control app, whose login does NOT work in INVmate II. And maybe this is why I cannot have my HA integration working.
I tried to use the INVmate II app as well, but my humidifier does not show, nor I can find its wifi access point.

Maybe my (new) dehumidifier is not compatible?
How to solve the issue?
Many thanks

**Comment by oliverbutler** [comment]
Did you ever manage to solve this?

**Comment by barban-dev** [comment]
> Hey @jlm70 @oliverbutler,
> 
> I think I've figured out a workaround for models that use the Inventor Control app- I noticed these devices' APs are called `SmartLife_xxxxx`, which is the same pattern used by the Tuya Smart app.
> 
> I removed my dehumidifier from the Inventor Control app and registered it with Tuya Smart (`Add Device` -> `Small Home Appliances` -> `Dehumidifier (Wi-Fi)` -> select `slow flashing` when dehumidifier shows `AP`).
> 
> Once the dehumidifier showed in the Tuya Smart app, I was able to use Home Assistant's built-in [Tuya cloud integration](https://www.home-assistant.io/integrations/tuya) to operate the device:
> 
> ![Home Assistant showing basic controls for an Inventor EVA ION Pro Wi-Fi](https://private-user-images.githubusercontent.com/5637/280742708-8877cd7a-be56-44d4-a2a2-df9ca2adf2e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODE0MTQsIm5iZiI6MTcwNDQ4MTExNCwicGF0aCI6Ii81NjM3LzI4MDc0MjcwOC04ODc3Y2Q3YS1iZTU2LTQ0ZDQtYTJhMi1kZjljYTJhZGYyZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTg1ODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ2NzI4ODk1ODRkM2UwNTAwMTc4MGU2NDIzN2FkZWI5Mjk4YjJkNTYyOTJmMmIzODA3MmI0Yzg4ZmZmM2IwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rsfve9P1CPsWFNLLcp79yDOz28-oB2U_DQOJ-7OGtMo)
> 
> While the Tuya Smart app has full control over the device, Home Assistant misses out on e.g., the water tank full sensor. https://github.com/tuya/tuya-home-assistant/blob/main/docs/develop_new_driver.md could be of use toward extending the Tuya integration, but that'd be off-topic for this repo 😄

Thnak you very much for these useful information.

**Comment by thargy** [comment]
I'm guessing this is still the case. Just bought the same model thinking it would be compatible and only found this when I got the login fail method. I'm assuming it still doesn't work.
