### ISSUE TITLE
[Suggestion] LAN and air conditioners

### ISSUE THREAD

**Issue by GrSoul** [barban-dev/homeassistant-midea-dehumidifier#7]
Ciao Andrea. Great work with your custom integration. Everything works as advertised. I have two suggestions:

1. For the most of my sensors and devices I cut them off the internet at the router level but I can still control them locally. In this integration it's not possible and that would be a good idea for a future update for privacy reasons. Maybe it's not possible at all though.

2. I also have an Inventor air conditioner so maybe I could run some tests of yours in order to make this integration a global Inventor add-on for HA. 

Grazie e arrivederci mio amico.
Chris

**Comment by barban-dev** [comment]
Hi, thanks for your suggestions.
Both proposals are great but I think it would be very time consuming to implement them.
Ciao!
